-- MySQL Script generated by MySQL Workbench
-- Thu Sep 15 15:49:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema car_services_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_services_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_services_db` DEFAULT CHARACTER SET utf8 ;
USE `car_services_db` ;

-- -----------------------------------------------------
-- Table `car_services_db`.`car_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`car_services` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`car_services` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`clients` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`clients` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `car_service_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `dob` TIMESTAMP NOT NULL,
  `registration_date` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clients_car_services1_idx` (`car_service_id` ASC),
  CONSTRAINT `fk_clients_car_services1`
    FOREIGN KEY (`car_service_id`)
    REFERENCES `car_services_db`.`car_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`departments` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`departments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `car_service_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_departments_car_services1_idx` (`car_service_id` ASC),
  CONSTRAINT `fk_departments_car_services1`
    FOREIGN KEY (`car_service_id`)
    REFERENCES `car_services_db`.`car_services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`employees` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`employees` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `dob` TIMESTAMP NOT NULL,
  `experience` INT NOT NULL,
  `profession` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_departments1_idx` (`department_id` ASC),
  CONSTRAINT `fk_employees_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `car_services_db`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`children`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`children` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`children` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `dob` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`tools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`tools` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`tools` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tools_departments1_idx` (`department_id` ASC),
  CONSTRAINT `fk_tools_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `car_services_db`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`discount_programs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`discount_programs` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`discount_programs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `discount` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_discount_programs_clients1_idx` (`client_id` ASC),
  CONSTRAINT `fk_discount_programs_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `car_services_db`.`clients` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`services` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`services` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` ENUM('CAR_PAINTING', 'ENGINEMAINTENANCE', 'ELECTRICAL_MAINTENANCE', 'SUSPENSION_MAINTENANCE') NOT NULL,
  `price_of_hour` DECIMAL NOT NULL,
  `work_time` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`prices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`prices` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`prices` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_id` BIGINT UNSIGNED NOT NULL,
  `performed_flag` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_prices_services1_idx` (`service_id` ASC),
  CONSTRAINT `fk_prices_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `car_services_db`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`materials` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`materials` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quantity` DECIMAL NOT NULL DEFAULT 0,
  `unit` VARCHAR(45) NOT NULL,
  `price_unit` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`cars` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`cars` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` BIGINT UNSIGNED NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `year_create` TIMESTAMP NOT NULL,
  `vin_code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cars_clients1_idx` (`client_id` ASC),
  CONSTRAINT `fk_cars_clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `car_services_db`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`employee_children`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`employee_children` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`employee_children` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` BIGINT UNSIGNED NOT NULL,
  `child_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_employees_has_children_children1_idx` (`child_id` ASC),
  INDEX `fk_employees_has_children_employees1_idx` (`employee_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employees_has_children_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `car_services_db`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_has_children_children1`
    FOREIGN KEY (`child_id`)
    REFERENCES `car_services_db`.`children` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`service_car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`service_car` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`service_car` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_id` BIGINT UNSIGNED NOT NULL,
  `car_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_service_work_times_has_cars_cars1_idx` (`car_id` ASC),
  INDEX `fk_service_work_times_has_cars_service_work_times1_idx` (`service_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_service_work_times_has_cars_service_work_times1`
    FOREIGN KEY (`service_id`)
    REFERENCES `car_services_db`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_work_times_has_cars_cars1`
    FOREIGN KEY (`car_id`)
    REFERENCES `car_services_db`.`cars` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_services_db`.`service_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_services_db`.`service_material` ;

CREATE TABLE IF NOT EXISTS `car_services_db`.`service_material` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_id` BIGINT UNSIGNED NOT NULL,
  `material_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_service_work_times_has_materials_materials1_idx` (`material_id` ASC),
  INDEX `fk_service_work_times_has_materials_service_work_times1_idx` (`service_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_service_work_times_has_materials_service_work_times1`
    FOREIGN KEY (`service_id`)
    REFERENCES `car_services_db`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_work_times_has_materials_materials1`
    FOREIGN KEY (`material_id`)
    REFERENCES `car_services_db`.`materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
